[package]

name = "hello-uni"
version = "0.0.1"
authors = ["Baptiste Covolato"]

[dependencies]

rust-libcore = "*"

[dependencies.uni]

git = "https://github.com/uni-rs/uni.rs.git"
features = [ "xen" ]
